import { createFileRoute } from "@tanstack/react-router";
import type { ReactNode } from "react";
import { Flame, Mountain, PawPrint, Sprout, UtensilsCrossed, Wind } from "lucide-react";
import meadow from "@/assets/khajjiar-meadow.png";
import paragliding from "@/assets/apple-garden-paragliding.png";
import temple from "@/assets/khajjiar-temple-view.png";
import { BookingBand, PageHero, SectionTitle, pageMeta } from "@/components/page-elements";

export const Route = createFileRoute("/experiences")({ head: () => pageMeta("Khajjiar Experiences | Apple Garden Homestay", "Explore Khajjiar nature, apple orchard calm, bonfire evenings, Himachali food, paragliding and pet-friendly mountain stays.", "/experiences"), component: ExperiencesPage });

function Experience({ icon, title, children }: { icon: ReactNode; title: string; children: ReactNode }) { return <article className="border-t border-border py-8"><div className="flex items-start gap-5"><span className="mt-1 text-primary">{icon}</span><div><h2 className="font-display text-3xl">{title}</h2><p className="mt-3 max-w-xl leading-7 text-muted-foreground">{children}</p></div></div></article> }
function ExperiencesPage() { return <><PageHero image={meadow} alt="Khajjiar meadow surrounded by cedar forests" eyebrow="Experiences" title="Let the mountains set the pace." description="Meadows, orchard quiet, local flavour and open-air adventure — experience Khajjiar in your own way." /><section className="section-shell"><div className="grid gap-14 lg:grid-cols-[.9fr_1.1fr]"><div className="lg:sticky lg:top-28 lg:self-start"><SectionTitle eyebrow="In and around Khajjiar" title="Days that feel wonderfully unplanned." /><div className="image-lift mt-10 h-[420px]"><img src={temple} alt="Temple and Himalayan peaks near Khajjiar" loading="lazy" className="size-full object-cover" /></div></div><div><Experience icon={<Mountain />} title="Khajjiar Nature">Explore the beautiful meadows, forests and mountain scenery around Khajjiar.</Experience><Experience icon={<Sprout />} title="Apple Orchard Experience">Enjoy the peaceful atmosphere of the apple garden surrounding the homestay.</Experience><Experience icon={<Flame />} title="Bonfire Evenings">Gather for a cozy evening around a bonfire when arranged by the property.</Experience><Experience icon={<UtensilsCrossed />} title="Himachali Food">Experience authentic local flavours prepared in a homestay environment.</Experience><Experience icon={<Wind />} title="Adventure">Ask about the available paragliding packages and activity assistance.</Experience><Experience icon={<PawPrint />} title="Pet-Friendly Stay">Enjoy the mountain setting together with your pets.</Experience></div></div></section><section className="relative isolate flex min-h-[620px] items-end overflow-hidden px-5 py-16 text-hero-foreground lg:px-8"><img src={paragliding} alt="Paraglider over the forests and valley near Apple Garden Homestay" loading="lazy" className="absolute inset-0 -z-20 size-full object-cover" /><div className="hero-shade absolute inset-0 -z-10" /><div className="mx-auto w-full max-w-[1500px]"><p className="eyebrow text-brand-soft">Adventure above the valley</p><h2 className="mt-4 max-w-2xl font-display text-5xl sm:text-6xl">A different view of Khajjiar.</h2></div></section><BookingBand /></> }